name: attention-toad
dependencies:
  - cudatoolkit=10.1
  - cudnn=7.6
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - python=3.7
  - scikit-learn
  - scipy
  - shapely
  - statsmodels
  - tensorflow-hub
  - tqdm
  - pip:
      - sobol-seq
      - tensorflow==2.3
